DRIVER_PATH                     = r"C:/SeleniumDrivers/chrome"
EXECUTABLE_PATH                 = r"C:/SeleniumDrivers/chrome/chromedriver.exe"
KELLER_URL                      = r"https://www.jjkellertraining.com/Account/Signin?ReturnUrl=%2fViews%2fDashboard%2fMyDashboard.aspx"
IMPLICIT_WAIT                   = 15
DEFAULT_LOCATION                = "345275"


LOGIN_PAGE_ID_EMAIL             = "ContentPlaceHolder1_txtEmail"
LOGIN_PAGE_ID_PASSWORD          = "ContentPlaceHolder1_txtPassword"
LOGIN_PAGE_ID_SIGNIN            = "ContentPlaceHolder1_ibtnSignIn"
LOGIN_PAGE_VAL_EMAIL            = "yshpatserman@gmail.com"
LOGIN_PAGE_VAL_PASSWORD         = "1940Odessa"

DASH_URL                        = r"https://www.jjkellertraining.com/Views/Dashboard/MyDashboard.aspx"
DASH_PAGE_ID_SIGNOUT            = "hlSignout"
DASH_PAGE_VAL_SIGNOUT           = "Sign Out"
DASH_PAGE_ATXT_MYSTUDENTS       = "My Students"
DASH_PAGE_ID_ONLINETRAINING     = "hlInteractiveTraining"

STUDENT_PAGE_ID_LASTNAME        = "ContentPlaceHolder1_txtLastName"
STUDENT_PAGE_ID_ID              = "ContentPlaceHolder1_txtEmployeeKey"
STUDENT_PAGE_ID_LOCATION        = "ContentPlaceHolder1_ddlLocation"
STUDENT_PAGE_VAL_LOCATION       = DEFAULT_LOCATION
STUDENT_PAGE_ID_SEARCH          = "ContentPlaceHolder1_ibtnSearch"
STUDENT_PAGE_ID_GRID            = "grid"
STUDENT_PAGE_ATT_TP_SEARCH      = "type"
STUDENT_PAGE_ATT_VAL_SEARCH     = "image"
STUDENT_PAGE_ROWS_PER_PAGE      = 50
STUDENT_PAGE_ID_STUD_COUNT      = "ContentPlaceHolder1_lblResultCount"
STUDENT_PAGE_ID_TBL_NAME_PRE    = "ContentPlaceHolder1_lvwEmployees_lbtnEditStudent_"
STUDENT_PAGE_ID_TBL_EMAIL_PRE   = "ContentPlaceHolder1_lvwEmployees_lblEmail_"
STUDENT_PAGE_ATXT_ADDSTUDREC    = "Add Student Record"

ADDSTUD_PAGE_ID_FIRSTNAME       = "ContentPlaceHolder1_txtFirstName"
ADDSTUD_PAGE_ID_LASTNAME        = "ContentPlaceHolder1_txtLastName"
ADDSTUD_PAGE_ID_LOCATION        = "ContentPlaceHolder1_ddlLocation"
ADDSTUD_PAGE_ID_EMAIL           = "ContentPlaceHolder1_txtEmail"
ADDSTUD_PAGE_ID_PHONE           = "ContentPlaceHolder1_txtMobilePhone"
ADDSTUD_PAGE_ID_ID              = "ContentPlaceHolder1_txtEmployeeId"
ADDSTUD_PAGE_ID_EMAIL_TYPE      = "type"
ADDSTUD_PAGE_ID_EMAIL_VAL       = "text"
ADDSTUD_PAGE_ID_BTN_SAVE        = "ContentPlaceHolder1_ibtnSave"

ENROLL_PAGE_CURRICULUM_URL_PRE  = r"https://www.jjkellertraining.com/Views/InteractiveTraining/CurriculumCourses.aspx?CID="
ENROLL_PAGE_ID_ENROLL_STUDENTS  = "ContentPlaceHolder1_lbtnEnrollStudents"
ENROLL_PAGE_STENRBATCH_URL_PRE  = r"https://www.jjkellertraining.com/Views/InteractiveTraining/StudentsEnrollBatch.aspx?ReturnToPage=CourseListKeller&CID="
ENROLL_PAGE_ID_PAGER_SEARCH     = "ContentPlaceHolder1_dtpagersearchresults"
ENROLL_PAGE_ID_LAST_NAME        = "ContentPlaceHolder1_txtLastName"
ENROLL_PAGE_ID_SEARCH           = "ContentPlaceHolder1_ibtnSearch"
ENROLL_PAGE_TBL_SEARCH_RES      = r"//*[@class='grid']/tbody/tr"
ENROLL_PAGE_TBL_NOT_FOUND       = "No student records found"
ENROLL_PAGE_TBL_STUDID_PRE      = "ContentPlaceHolder1_lvEmployees_lblEmployeeId_"
ENROLL_PAGE_TBL_STUDSEL_PRE     = "ContentPlaceHolder1_lvEmployees_chkSelect_"
ENROLL_PAGE_ID_CONTINUE         = "ContentPlaceHolder1_ibtnContinueTop"
ENROLL_PAGE_ID_CHECKALL         = "ContentPlaceHolder1_lvCourses_CheckBoxHeader"
ENROLL_PAGE_ID_CONTINUE2        = "ContentPlaceHolder1_ibtnContinueTop"
ENROLL_PAGE_ID_SEL_SCORE        = "ContentPlaceHolder1_drpQuickSet"
ENROLL_PAGE_VAL_SEL_SCORE       = "80"
ENROLL_PAGE_ID_APPLY            = "ContentPlaceHolder1_ibtnApplyQuickSet"
ENROLL_PAGE_ID_CONTINUE3        = "ContentPlaceHolder1_ibtnContinue"
ENROLL_PAGE_EXPIRATION_DAYS     = 93
ENROLL_PAGE_REMIND_BEFORE_EXP   = 10
ENROLL_PAGE_DATE_FORMAT         = r"%m/%d/%Y"
ENROLL_PAGE_ID_REMINDER         = "ContentPlaceHolder1_txtCourseReminderDate"
ENROLL_PAGE_ID_EXPIRATION       = "ContentPlaceHolder1_txtCourseExpirationDate"
ENROLL_PAGE_ID_CONTINUE4        = "ContentPlaceHolder1_btnContinue"
ENROLL_PAGE_ID_CONTINUE5        = "ContentPlaceHolder1_ibtnContinue"
ENROLL_PAGE_ID_COMPLETE_ENROLL  = "ContentPlaceHolder1_ibtnCompleteEnrollment"

VERIFY_PAGE_STUDENTS_PAGE       = r"https://www.jjkellertraining.com/Views/TrainingRecords/MyRecords.aspx"
VERIFY_PAGE_ID_RECORD_ONE       = "ContentPlaceHolder1_lvwEmployees_lbtnEditStudent_0"
VERIFY_PAGE_ID_REC_37           = "ContentPlaceHolder1_lvwTrainingHistory_lblCourseTitle_37"